# Generated by Django 4.0.4 on 2022-06-03 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_medical_status_patient_symptoms_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='photo',
            field=models.ImageField(upload_to='photos/'),
        ),
    ]
