# Generated by Django 4.0.4 on 2022-06-04 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_patient_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('Mobil', models.CharField(max_length=30)),
                ('Email', models.EmailField(max_length=50)),
                ('date', models.DateField()),
                ('upload', models.FileField(upload_to='uploads/%Y/%m/%d/')),
                ('time', models.DateTimeField(choices=[('1', '8:00 to 9:00'), ('2', '9:00 to 10:00'), ('3', '10:00 to 1:00')])),
            ],
        ),
        migrations.AlterField(
            model_name='patient',
            name='photo',
            field=models.ImageField(upload_to='photos/%Y/%m/%d'),
        ),
    ]
