# Generated by Django 4.0.4 on 2022-06-04 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_appointment_alter_patient_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='upload',
            field=models.FileField(upload_to='uploads/%Y/%m/%d'),
        ),
    ]
